---
title: "The Impact of Environmental Taxation on CO2 Emissions"
subtitle: "Statistical Methods for Causal Inference"
author: "**Sonia Mendizábal and Wanchao Zhao**"
date: "2024-07-19"
format: 
  revealjs:
    slide-number: true
    toc: true
    toc-depth: 1
    toc-title: Agenda
    toc-location: right
    number-sections: false
    fontsize: 1.9em
    chalkboard: 
      buttons: false
    preview-links: auto
    css: styles.css
editor: visual
---

# Introduction

This project aims to evaluate the impact of taxes on reducing emissions. By analyzing historical data, policy implementations, and economic indicators, we will assess the effectiveness of carbon taxes in promoting sustainable environmental practices and reducing carbon footprints.


# Design

Balanced panel data with staggered adoption of treatment with general pattern (switch on and off)


## Data


## Variables


# Theory

We use a simple framework of counterfactual estimation for causal inference with time-series cross-sectional data, in which we estimate the average treatment effect on the treated by directly imputing counterfactual outcomes for treated observations.



## Fixed effects counterfactual estimator (FEct)


## Interactive fixed effects counterfactual estimator (IFEct)


## Matrix completion estimator (MC)




# Results




# Conclusions

# References
